config: 
  ci_implementation: 'travis'
  ci_host: 'http://travis-ci.org'
  job_name: 'bonnie'
  repository_name: 'pophealth'
  poll_interval: '30s'
  blink_interval: '2s'
  blink_off_time: 1
  sounds:
    success: './sounds/success.wav'
    failure: './sounds/failure.aiff'
  play_sounds: true
