config: 
  ci_host: 'http://bucket.mitre.org/hudson/'
  job_name: 'popHealth Web Application'
  poll_interval: '10s'
  blink_interval: '2s'
  blink_off_time: 1
  sounds:
    success: './sounds/success.wav'
    failure: './sounds/failure.aiff'
  play_sounds: true
