config: 
  ci_implementation: 'travis'
  ci_host: 'http://travis-ci.org'
  job_name: 'popHealth'
  repository_name: 'pophealth'
  poll_interval: '10s'
  sounds:
    success: './sounds/success.wav'
    failure: './sounds/failure.aiff'
  play_sounds: true
